version: '3.8'

services:
  nginx:
    build: ./frontend/nginx
    container_name: nginx-ssl
    ports:
      - "80:80"
      - "443:443"
  node:
    build: ./frontend/roulette
    container_name: node-app
    ports:
      - "3000:3000"
  golang:
    build: ./backend
    container_name: calculate
    ports:
      - "8080:8080"
