version: '3.8'

services:
  frontend:
    build: ./frontend/roulette-front  # Путь к фронтенд-директории
    ports:
      - "80:80"  # Пробрасываем порт для доступа к фронтенду
    networks:
      - app-network
    depends_on:
      - backend  # Указываем зависимость от бэкенда

  backend:
    build: ./backend  # Путь к бэкенд-директории
    ports:
      - "8080:8080"  # Пробрасываем порт для доступа к API
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
