version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot
    networks:
      - app-network
    expose:
      - "5432" 
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/telegram_bot?sslmode=disable
    networks:
      - app-network
    command: ["sh", "-c", "sleep 10 && ./bot"]
  nginx:
    build: 
      context: ./frontend/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem
      - /etc/letsencrypt/live/supreme-roulette.work.gd/fullchain.pem:/etc/letsencrypt/live/supreme-roulette.work.gd/fullchain.pem
      - /etc/letsencrypt/live/supreme-roulette.work.gd/privkey.pem:/etc/letsencrypt/live/supreme-roulette.work.gd/privkey.pem
      - /etc/letsencrypt/live/supreme-roulette.work.gd/chain.pem:/etc/letsencrypt/live/supreme-roulette.work.gd/chain.pem
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/roulette-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge